version: '3'

services:
  tfx:
    image: tensorflow/tfx:1.12.0
    ports:
      - "8888:8888"
      - "6006:6006"
    volumes:
      - ".:/tfx/src"
    entrypoint: /run_jupyter.sh
    stdin_open: true
    tty: true
    container_name: tfx
    restart: "no"
