feature {
  name: "Cover_Type"
  type: INT
  int_domain {
    name: "Cover_Type"
    min: 0
    max: 6
    is_categorical: true
  }
  presence {
    min_fraction: 1.0
    min_count: 1
  }
  not_in_environment: "SERVING"
  shape {
    dim {
      size: 1
    }
  }
}
feature {
  name: "Elevation"
  type: INT
  int_domain {
    name: "Elevation"
    min: 1860
    max: 3858
  }
  presence {
    min_fraction: 1.0
    min_count: 1
  }
  shape {
    dim {
      size: 1
    }
  }
}
feature {
  name: "Horizontal_Distance_To_Roadways"
  type: INT
  int_domain {
    name: "Horizontal_Distance_To_Roadways"
    min: 0
    max: 7116
  }
  presence {
    min_fraction: 1.0
    min_count: 1
  }
  shape {
    dim {
      size: 1
    }
  }
}
feature {
  name: "Soil_Type_C2703"
  type: INT
  int_domain {
    name: "Soil_Type_C2703"
    min: 0
    max: 1
    is_categorical: true
  }
  presence {
    min_fraction: 1.0
    min_count: 1
  }
  shape {
    dim {
      size: 1
    }
  }
}
feature {
  name: "Soil_Type_C2704"
  type: INT
  int_domain {
    name: "Soil_Type_C2704"
    min: 0
    max: 1
    is_categorical: true
  }
  presence {
    min_fraction: 1.0
    min_count: 1
  }
  shape {
    dim {
      size: 1
    }
  }
}
feature {
  name: "Soil_Type_C2705"
  type: INT
  int_domain {
    name: "Soil_Type_C2705"
    min: 0
    max: 1
    is_categorical: true
  }
  presence {
    min_fraction: 1.0
    min_count: 1
  }
  shape {
    dim {
      size: 1
    }
  }
}
feature {
  name: "Soil_Type_C2717"
  type: INT
  int_domain {
    name: "Soil_Type_C2717"
    min: 0
    max: 1
    is_categorical: true
  }
  presence {
    min_fraction: 1.0
    min_count: 1
  }
  shape {
    dim {
      size: 1
    }
  }
}
feature {
  name: "Soil_Type_C4703"
  type: INT
  int_domain {
    name: "Soil_Type_C4703"
    min: 0
    max: 1
    is_categorical: true
  }
  presence {
    min_fraction: 1.0
    min_count: 1
  }
  shape {
    dim {
      size: 1
    }
  }
}
feature {
  name: "Soil_Type_C8771"
  type: INT
  int_domain {
    name: "Soil_Type_C8771"
    min: 0
    max: 1
    is_categorical: true
  }
  presence {
    min_fraction: 1.0
    min_count: 1
  }
  shape {
    dim {
      size: 1
    }
  }
}
feature {
  name: "Soil_Type_C8772"
  type: INT
  int_domain {
    name: "Soil_Type_C8772"
    min: 0
    max: 1
    is_categorical: true
  }
  presence {
    min_fraction: 1.0
    min_count: 1
  }
  shape {
    dim {
      size: 1
    }
  }
}
feature {
  name: "Wilderness_Area_Rawah"
  type: INT
  int_domain {
    name: "Wilderness_Area_Rawah"
    min: 0
    max: 1
  }
  presence {
    min_fraction: 1.0
    min_count: 1
  }
  shape {
    dim {
      size: 1
    }
  }
}
default_environment: "TRAINING"
default_environment: "SERVING"
